# pre-commit autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^tests/.*\.json$|^tests/.*\.json5$|^tests/.*\.errorSpec$|^tests/.*\.txt$|^tests/.*\.js$
      - id: trailing-whitespace
        exclude: ^tests/.*\.json$|^tests/.*\.json5$
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          [--remove-all-unused-imports, --remove-unused-variables, --in-place]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: uv run isort
        types: [python]
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: uv run flake8
        types: [python]
        language: system
        pass_filenames: false
        args: [src, tests]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        args: [
            src,
            tests,
            -rn, # Only display messages
            -sn, # Don't display the score
            --rcfile=.pylintrc,
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.2
    hooks:
      - id: cspell # Spell check changed files
      - id: cspell # Spell check the commit message
        name: check commit message spelling
        args:
          - --no-must-find-files
          - --no-progress
          - --no-summary
          - --files
          - .git/COMMIT_EDITMSG
        stages: [commit-msg]
        always_run: true
