name: benchmark

on:
    # push:
    #   branches: ["main"]
    # pull_request:
    #   branches: ["main"]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1,2,3,4,5]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv sync --group dev

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        env:
          CI_ENV: true
        with:
          run: uv run pytest tests/ --codspeed --test-group=${{ matrix.shard }} --test-group-count=5
          token: ${{ secrets.CODSPEED_TOKEN }}
