name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  develop:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv venv
          uv pip install --upgrade pip
          uv sync

      - name: Run pytest with coverage
        run: |
          uv run pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/.coverage/cov.xml
          flags: pytest
      - name: Upload results
        uses: trunk-io/analytics-uploader@main
        with:
          junit-paths: ./tests/.coverage/cov.xml
          org-slug: austinyu
          token: ${{ secrets.TRUNK_API_TOKEN }}
        continue-on-error: true

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true

      - name: Build package
        run: |
          uv build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ runner.os }}-py${{ matrix.python-version }}
          path: dist/*
