# Simple workflow for deploying static content to GitHub Pages
name: build docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: |
          uv venv
          uv pip install --upgrade pip
          uv sync --group docs
      - name: Build docs
        run: |
          uv run mkdocs build

      - name: Upload docs to artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: site/
